[ 2024-12-29 10:58:57,897 ] 22 root - INFO - Exported train and test file path.
[ 2024-12-29 10:59:06,325 ] 96 pymongo.serverSelection - INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 6770de22114f1ee538fb49e0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('cluster0-shard-00-01.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('cluster0-shard-00-02.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6770de22114f1ee538fb49e0"}, "remainingTimeMS": 30}
[ 2024-12-29 10:59:16,193 ] 66 root - INFO - Performed train test split on the dataframe
[ 2024-12-29 10:59:16,193 ] 68 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-12-29 10:59:16,193 ] 76 root - INFO - Exporting train and test file path.
[ 2024-12-29 10:59:16,342 ] 85 root - INFO - Exported train and test file path.
[ 2024-12-29 10:59:16,342 ] 27 root - INFO - Data Ingestion is completed
[ 2024-12-29 10:59:16,342 ] 28 root - INFO - Data Validataion initiated
[ 2024-12-29 10:59:16,475 ] 32 root - INFO - Required number of columns is 2
[ 2024-12-29 10:59:16,475 ] 33 root - INFO - Dataframe has columns:31
[ 2024-12-29 10:59:16,475 ] 32 root - INFO - Required number of columns is 2
[ 2024-12-29 10:59:16,475 ] 33 root - INFO - Dataframe has columns:31
[ 2024-12-29 10:59:16,845 ] 34 root - INFO - Data Validataion is completed
[ 2024-12-29 10:59:16,845 ] 35 root - INFO - Data Transformation initiated
[ 2024-12-29 10:59:16,845 ] 63 root - INFO - Entered Data Transformation stage
[ 2024-12-29 10:59:16,917 ] 50 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2024-12-29 10:59:16,917 ] 55 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2024-12-29 10:59:16,937 ] 47 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-29 10:59:16,943 ] 51 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-29 10:59:16,943 ] 47 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-29 10:59:16,949 ] 51 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-29 10:59:16,949 ] 41 root - INFO - Data Transformation completed
[ 2024-12-29 10:59:16,949 ] 44 root - INFO - Model Training sstared
[ 2024-12-29 11:08:42,541 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC096708E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/log-model
[ 2024-12-29 11:08:49,173 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC09E36B60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/log-model
[ 2024-12-29 11:08:59,376 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E76380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/log-model
[ 2024-12-29 11:09:18,235 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E77610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/log-model
[ 2024-12-29 11:09:53,023 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E76B60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/log-model
[ 2024-12-29 11:09:57,079 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC09627CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:10:03,458 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC09625510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:10:13,720 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E76D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:10:31,833 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC0965E680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:11:06,329 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E764A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:11:10,397 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC0965FC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:11:16,611 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC0965DC00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:11:26,945 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC0965E3B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:11:45,456 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC09E90730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
[ 2024-12-29 11:12:19,583 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC10E86A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=1312555dd02242aca2209014a7d8aa92&run_id=1312555dd02242aca2209014a7d8aa92
