[ 2024-12-29 09:56:50,011 ] 22 root - INFO - Exported train and test file path.
[ 2024-12-29 09:56:58,370 ] 96 pymongo.serverSelection - INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 6770cf92a82df5a812d51b09, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('cluster0-shard-00-01.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('cluster0-shard-00-02.pcljl.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6770cf92a82df5a812d51b09"}, "remainingTimeMS": 30}
[ 2024-12-29 09:57:08,674 ] 66 root - INFO - Performed train test split on the dataframe
[ 2024-12-29 09:57:08,674 ] 68 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-12-29 09:57:08,674 ] 76 root - INFO - Exporting train and test file path.
[ 2024-12-29 09:57:08,854 ] 85 root - INFO - Exported train and test file path.
[ 2024-12-29 09:57:08,854 ] 27 root - INFO - Data Ingestion is completed
[ 2024-12-29 09:57:08,854 ] 28 root - INFO - Data Validataion initiated
[ 2024-12-29 09:57:08,977 ] 32 root - INFO - Required number of columns is 2
[ 2024-12-29 09:57:08,977 ] 33 root - INFO - Dataframe has columns:31
[ 2024-12-29 09:57:08,977 ] 32 root - INFO - Required number of columns is 2
[ 2024-12-29 09:57:08,977 ] 33 root - INFO - Dataframe has columns:31
[ 2024-12-29 09:57:09,345 ] 34 root - INFO - Data Validataion is completed
[ 2024-12-29 09:57:09,345 ] 35 root - INFO - Data Transformation initiated
[ 2024-12-29 09:57:09,345 ] 63 root - INFO - Entered Data Transformation stage
[ 2024-12-29 09:57:09,434 ] 50 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2024-12-29 09:57:09,435 ] 55 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2024-12-29 09:57:09,449 ] 47 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-29 09:57:09,459 ] 51 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-29 09:57:09,459 ] 47 root - INFO - Entered the save_object method of MainUtils class
[ 2024-12-29 09:57:09,469 ] 51 root - INFO - Exited the save_object method of MainUtils class
[ 2024-12-29 09:57:09,469 ] 41 root - INFO - Data Transformation completed
[ 2024-12-29 09:57:09,469 ] 44 root - INFO - Model Training sstared
[ 2024-12-29 10:06:14,270 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018825FCF7C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-29 10:06:23,051 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018825FCF340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-29 10:06:35,791 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018826E3B4C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-29 10:06:56,051 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001882AD30730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-29 10:07:32,422 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018825FFC340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
